# Generated by Django 3.2 on 2021-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_filters_test_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.IntegerField(default=0)),
                ('image_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='filters',
            name='filterType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filters',
            name='userid',
            field=models.IntegerField(default=-1),
        ),
    ]
