# Generated by Django 3.2 on 2021-05-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210525_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='userid',
            field=models.CharField(default='-1', max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='userid',
            field=models.CharField(max_length=200),
        ),
    ]
